name: cursor_autocomplete_options
description: Add autocomplete dialog options to the cursor of a textfield.
version: 1.7.0
site: https://igormidev.github.io/cursor_autocomplete_options
homepage: https://igormidev.github.io/cursor_autocomplete_options
repository: https://github.com/igormidev/cursor_autocomplete_options
issue_tracker: https://github.com/igormidev/cursor_autocomplete_options/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_debouncer: ^1.1.0
  
flutter: 
  uses-material-design: true

screenshots:
  - description: A visual demonstration of the cursor.
    path: art/showcase-1.png

topics:
  - layout
  - ui-component
