name: cursor_autocomplete_options
description: Add autocomplete dialog options to the cursor of a textfield.
version: 1.1.0
homepage: https://github.com/igormidev/cursor_autocomplete_options
repository: https://github.com/igormidev/cursor_autocomplete_options

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter: 

screenshots:
  - description: A visual demonstration of the cursor.
    path: art/showcase-1.png

topics:
  - layout
  - ui